server:
  port: 8758

spring:
  application:
    name: cinema
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:8768/cinema_db
    username: cinema_user
    password: cinema_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    screening-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

axon:
  axonserver:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  use-fqn: true