server:
  port: 8758

spring:
  application:
    name: cinema
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:8768/cinema_db
    username: cinema_user
    password: cinema_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    screening-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: false

axon:
  axonserver:
    enabled: false
  timeout:
    enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  use-fqn: true

slices:
  dayschedule:
    write:
      cancelscreening:
        enabled: true
      schedulescreening:
        enabled: true
      createschedule:
        enabled: true
    read:
      searchscreenings:
        enabled: true
      getschedulebyid:
        enabled: true
    automation:
      whenscreeningscheduledthenplaceseats:
        enabled: true
  seatsblocking:
    write:
      blockseat:
        enabled: true
      blockseats:
        enabled: true
      placeseat:
        enabled: true
    automation:
      trendsreporter:
        enabled: true
  adminnotifications:
    write:
      readnotification:
        enabled: true
      sendnotification:
        enabled: true
      starnotification:
        enabled: true
    automation:
      notificationviaemail:
        enabled: true
  issues:
    write:
      openissue:
        enabled: true
    automation:
      aiissueforwarder:
        enabled: true
  reservations:
    write:
      startreservation:
        enabled: true
      confirmseats:
        enabled: true
      cancelreservation:
        enabled: true
      collectreservation:
        enabled: true
    automation:
      blockingseats:
        enabled: true
      reservationexpiration:
        enabled: true